# -*- coding: utf-8 -*-
"""MSDS Exploration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GGISKp9fi0CpCwz4G70rVT4MRgkCKD9e
"""

import pandas as pd

month_urls_2023 = {'dec' : 'https://files.digital.nhs.uk/33/29837B/msds-dec2023-exp-measures.csv',
'nov' : 'https://files.digital.nhs.uk/F5/3EA7CF/msds-nov2023-exp-measures-final.csv',
'oct' : 'https://files.digital.nhs.uk/26/3027D9/msds-oct2023-exp-measures.csv',
'sep' : 'https://files.digital.nhs.uk/46/5C4FA7/msds-sep2023-exp-measures.csv',
'aug' : 'https://files.digital.nhs.uk/89/B1B69A/msds-aug2023-exp-measures-final.csv',
'july' : 'https://files.digital.nhs.uk/E3/4AD26C/msds-jul2023-exp-measures-final.csv',
'june' : 'https://files.digital.nhs.uk/81/A668F8/msds-jun2023-exp-measures-final.csv',
'may' : 'https://files.digital.nhs.uk/58/F842D9/msds-may2023-exp-measures-final.csv',
'apr' : 'https://files.digital.nhs.uk/2D/998529/msds-apr2023-exp-measures-final.csv',
'mar' : 'https://files.digital.nhs.uk/69/D4E641/msds-mar2023-exp-measures-final.csv',
'feb' : 'https://files.digital.nhs.uk/B4/B551EA/msds-feb2023-exp-measures.csv',
'jan' : 'https://files.digital.nhs.uk/26/CCBCCC/msds-jan2023-exp-measures.csv'}

month_urls_2024 = {'nov':'https://files.digital.nhs.uk/F4/CF7A0B/msds-nov2024-exp-data.csv',
                   'dec':'https://files.digital.nhs.uk/6E/CC3FC4/msds-dec2024-exp-data.csv',
                   'oct':'https://files.digital.nhs.uk/D2/EC1099/msds-oct2024-exp-data.csv',
                   'sep':'https://files.digital.nhs.uk/D8/DCBAB8/msds-sep2024-exp-data.csv',
                   'aug':'https://files.digital.nhs.uk/9D/AAAA86/msds-aug2024-exp-data.csv',
                   'july':'https://files.digital.nhs.uk/30/B19CDD/msds-jul2024-exp-data.csv',
                   'june':'https://files.digital.nhs.uk/9C/6F6B1B/msds-jun2024-exp-data.csv',
                   'may':'https://files.digital.nhs.uk/9F/7F5835/msds-may2024-exp-data.csv',
                   'apr':'https://files.digital.nhs.uk/B7/9D3FA9/msds-apr2024-exp-data.csv',
                   'mar':'https://files.digital.nhs.uk/B2/24691F/msds-mar2024-exp-data.csv',
                   'feb':'https://files.digital.nhs.uk/60/D1D5F8/msds-feb2024-exp-data.csv',
                   'jan':'https://files.digital.nhs.uk/B9/B48FFB/msds-jan2024-exp-data.csv'}

month_urls_2025 = {'july':'https://files.digital.nhs.uk/2E/0AF065/msds-jul2025-exp-data.csv',
                   'june':'https://files.digital.nhs.uk/21/3CEC86/msds-jun2025-exp-data.csv',
                   'may':'https://files.digital.nhs.uk/E9/BDE3F8/msds-may2025-exp-data.csv',
                   'apr':'https://files.digital.nhs.uk/50/A42CCF/msds-apr2025-exp-data.csv',
                   'mar':'https://files.digital.nhs.uk/2F/B1EC9C/msds-mar2025-exp-data.csv',
                   'feb':'https://files.digital.nhs.uk/E1/2CA6EC/msds-feb2025-exp-data.csv',
                   'jan':'https://files.digital.nhs.uk/BE/E47BBB/msds-jan2025-exp-data.csv'}


years = {2023:month_urls_2023,
         2024:month_urls_2024,
         2025:month_urls_2025}

month_order = ['jan','feb','mar','apr','may','june','july','aug','sep','oct','nov','dec']

columns_dict = {'RPStartDate':'ReportingPeriodStartDate',
                'RPEndDate':'ReportingPeriodEndDate',
                'Indicator':'Dimension',
                'Value':'Final_value',
                'Currency':'Measure',
                'IndicatorFamily':'Count_Of'}
msds={}
for year in years:
  months = {}
  for month in years[year]:
    months[month] = pd.read_csv(years[year][month])
  msds[year]=pd.concat(months).rename(columns=columns_dict).reindex(index=month_order,
                                                       level=0)
df = pd.concat(msds)
df

df.Dimension.unique()

{x for x in df.Dimension if 'Weig' in x}

for i in df.Org_Name.unique():
  print(i)

{x for x in df.Org_Name if 'SAND' in x}

df.columns

place = 'UHB'
org_name = "SANDWELL AND WEST BIRMINGHAM HOSPITALS NHS TRUST"
mask1 = df.Org_Name == org_name
mask2 = df.Dimension.isin({x for x in df.Dimension if 'BMI' in x})
induction_data = df[mask1&mask2][['Measure','Final_value','Dimension']].reset_index()#.drop('level_2',axis=1)
ind_pivot = induction_data.pivot(columns='Measure',
                     index=['level_0','level_1','Dimension',],values='Final_value')


#ind_pivot.Rate.unstack().loc[:,month_order,:].to_csv(f'BMI Distribution {place}.csv')
ind_pivot.Rate.unstack().loc[:,month_order,:]#.astype(int).sum()

df[mask1&mask2]

def month_denoms(dim,org_name,year):
  mask1 = df.Org_Name == org_name
  mask2 = df.Dimension.isin({x for x in df.Dimension if dim in x})
  mask3 = df.ReportingPeriodStartDate.str.contains(year)
  return df[mask1&mask2&mask3].reset_index().groupby('level_1').sum()['Final_value'].reindex(index=month_order)#.sum()


dim = 'TotalDeliveries'
org_name = "BIRMINGHAM WOMEN'S AND CHILDREN'S NHS FOUNDATION TRUST"
year = '2025'

dim_dict = {}
for i in ['TotalDeliveries','TotalBookings','TotalBabies']:
  dim_dict[i] = month_denoms(i,org_name,year)
pd.concat(dim_dict,axis=1)

mask1 = df.Org_Name == org_name
mask2 = df.Dimension=='DeliveryMethodBabyGroup'
mask3 = df.Measure=='Denominator'
df[mask1&mask2].reset_index().groupby('level_1').sum()['Final_value']#.sum()

ind_pivot.Denominator.unstack().BMI_Normal.astype(int).sum()

"""# Preeclampsia distribution by trust"""

df.head()

df.Org_Level.unique()

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('whitegrid')
fig, ax = plt.subplots(figsize=(12,5))
display(asp.Value.astype(float).describe())
plt.bar(x=range(len(asp.Value.astype(float).sort_values())),
        height=asp.Value.astype(float).sort_values(),
        color='black',linewidth=0.1,width=0.95,
        edgecolor='white')#hist(bins=50)
plt.tick_params(
    axis='x',          # changes apply to the x-axis
    which='both',      # both major and minor ticks are affected
    bottom=True,      # ticks along the bottom edge are off
    top=False,         # ticks along the top edge are off
    labelbottom=False) # labels along the bottom edge are off

mask1 = (df.Indicator=='Aspirin_MeetCriteria')
mask2 = (df.Org_Level=='Provider')
mask3 = df.Currency.isin(['Numerator','Denominator'])
asp = df[mask1&mask2&mask3]
asp = asp.reset_index()[['Org_Name','level_0','Currency','Value']]
asp.Value = asp.Value.astype(int)
aspPivot = asp.pivot(columns='Currency',index=['Org_Name','level_0'],
          values='Value').reset_index().groupby('Org_Name').sum()
aspPivot.loc[:,'Rate']=(aspPivot.Numerator / aspPivot.Denominator)
aspannual = aspPivot.sort_values(by='Rate').drop('level_0',axis=1)
fig, ax = plt.subplots(figsize=(12,5))
display(aspannual.Rate.describe())
aspannual.Rate.plot.bar(ax=ax,
                        width=1,linewidth=0.05)
plt.tick_params(
    axis='x',          # changes apply to the x-axis
    which='both',      # both major and minor ticks are affected
    bottom=True,      # ticks along the bottom edge are off
    top=False,         # ticks along the top edge are off
    labelbottom=False) # labels along the bottom edge are off

aspannual.reset_index()[aspannual.reset_index()['Org_Name'].isin([x for x in aspannual.index if 'SHREW' in x])]

52/123

aspannual.loc[[x for x in aspannual.index if 'SHREW' in x]]

{x  for x in df.Indicator if 'eth' in x}